language: ruby
rvm: truffleruby

env:
  - TRUFFLERUBY_RECOMPILE_OPENSSL=false
install:
  - echo "$rvm_gem_options"
  - cat ~/.rvmrc
  - (for f in $HOME/.rvm/log/*truffleruby*/*.log; do echo $f; cat $f; done) || true
script:
  - ruby -v
  - git clone --branch test-travisci https://github.com/eregon/truffleruby.git
  - cd truffleruby
  - export JT='tool/jt.rb'
  - export AOT_BIN=`which ruby`
  - $JT test specs --native :library_cext
  - $JT test mri --native --openssl
  - cd ..
  - ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
  - git clone https://github.com/socketry/nio4r.git
  - cd nio4r
  - travis_retry bundle install --without development
  - cd ..
